# Generated by Django 3.1.4 on 2020-12-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_forme_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Entrer la présentation de produit (exemple: Bte de 12 ...)', max_length=200)),
                ('n_amm', models.CharField(max_length=100)),
            ],
        ),
    ]
