# Generated by Django 3.1.4 on 2020-12-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_presentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_composant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Matière première, Article de conditionnement primaire...', max_length=100)),
            ],
        ),
    ]
