# Generated by Django 3.1.4 on 2020-12-12 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_type_composant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_composant', models.CharField(max_length=100)),
                ('designation_composant', models.CharField(max_length=100)),
                ('principe_actif', models.BooleanField(default=False)),
                ('dosage_maximum', models.DecimalField(decimal_places=10, max_digits=19)),
                ('dosage_minimum', models.DecimalField(decimal_places=10, max_digits=19)),
                ('type_composant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_app.type_composant')),
            ],
        ),
    ]
