# Generated by Django 3.1.4 on 2020-12-12 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0006_type_parametre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_parametre', models.CharField(max_length=100)),
                ('valeur_maximum', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valeaur_minimum', models.DecimalField(decimal_places=10, max_digits=19)),
                ('type_parametre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_app.type_parametre')),
                ('unite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_app.unite')),
            ],
        ),
    ]
