# Generated by Django 3.1.4 on 2020-12-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0007_parametre_unite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_equipement', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('reference_rapport_qi', models.CharField(max_length=100)),
                ('reference_rapport_qo', models.CharField(max_length=100)),
                ('reference_rapport_qp', models.CharField(max_length=100)),
                ('date_qi', models.DateField(blank=True, null=True)),
                ('date_qo', models.DateField(blank=True, null=True)),
                ('date_qp', models.DateField(blank=True, null=True)),
                ('date_prochaine_qp', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
