# Generated by Django 3.1.4 on 2020-12-13 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0008_equipement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit_fini',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_produit', models.CharField(max_length=100)),
                ('designation_produit', models.CharField(max_length=100)),
                ('dosage', models.PositiveIntegerField()),
                ('rendement_global_minimal_acceptable', models.PositiveIntegerField()),
                ('valeur_max_rdt_fab_acc', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valeur_min_rdt_fab_acc', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valeur_max_rdt_comp_acc', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valeur_min_rdt_comp_acc', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valeur_max_rdt_meg_acc', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valeur_min_rdt_meg_acc', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valeur_max_rdt_pel_acc', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valeur_min_rdt_pel_acc', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valeur_max_rdt_cond1_acc', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valeur_min_rdt_cond1_acc', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valeur_max_rdt_cond2_acc', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valeur_min_rdt_cond2_acc', models.DecimalField(decimal_places=10, max_digits=19)),
                ('composant', models.ManyToManyField(to='new_app.Composant')),
                ('equipement', models.ManyToManyField(to='new_app.Equipement')),
                ('forme_produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_app.forme_produit')),
                ('parametre', models.ManyToManyField(to='new_app.Parametre')),
                ('presentation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_app.presentation')),
            ],
        ),
    ]
