# Generated by Django 3.1.4 on 2020-12-13 17:59

import django.core.validators
from django.db import migrations, models
import new_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0009_produit_fini'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), new_app.models.max_value_current_year], verbose_name='year')),
            ],
        ),
    ]
