# Generated by Django 3.1.4 on 2020-12-13 18:17

import django.core.validators
from django.db import migrations, models
import new_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0010_exercice_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AddField(
            model_name='exercice',
            name='year',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1984), new_app.models.max_value_current_year], verbose_name='year'),
        ),
    ]
