# Generated by Django 3.1.4 on 2020-12-13 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0011_auto_20201213_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type_anomalie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(max_length=100)),
                ('date_fabrication', models.DateField(blank=True, null=True)),
                ('date_peremption', models.DateField(blank=True, null=True)),
                ('taille_reelle_lot', models.DecimalField(decimal_places=0, max_digits=8)),
                ('protocole_validation_process', models.CharField(max_length=100)),
                ('protocole_validation_analytique', models.CharField(max_length=100)),
                ('reference_technique_controle', models.CharField(max_length=100)),
                ('valeur_prod_melange', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valeur_prod_compression', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valeur_prod_pelliculage', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valeur_prod_cond1', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valeur_prod_cond2', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valeur_cq_ph', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valeur_cq_micro_bio', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valeur_stabilite_ph', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valeur_stabilite_micro_bio', models.DecimalField(decimal_places=10, max_digits=19)),
                ('echeance_stabilite', models.DecimalField(decimal_places=0, max_digits=8)),
                ('valeur_rdt_fab', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valeur_rdt_comp', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valeur_rdt_meg', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valeur_rdt_pel', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valeur_rdt_cond1', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valeur_rdt_cond2', models.DecimalField(decimal_places=10, max_digits=19)),
                ('anomalie_cloturee', models.BooleanField(default=False)),
                ('num_lot_composant', models.CharField(max_length=100)),
                ('fabricant_composant', models.CharField(max_length=100)),
                ('dosage_pa', models.DecimalField(decimal_places=10, max_digits=19)),
                ('capa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_app.capa')),
                ('exercice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_app.exercice')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_app.produit_fini')),
                ('type_anomalie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_app.type_anomalie')),
            ],
        ),
    ]
